### ISSUE TITLE
Use newer Ubuntu LTS version 22.04

### ISSUE THREAD

**Issue by julian-alarcon** [techiescamp/vagrant-kubeadm-kubernetes#16]
As Ubuntu 22.04 Jammy Jellyfish is a LTS release, it will be better to migrate scripts/images to use this version.

This depends on: https://github.com/cri-o/cri-o/issues/5838 and https://github.com/chef/bento/issues/1405

**Comment by et304383** [comment]
I support this... **eventually**.  Ubuntu LTS releases are rarely stable in the first few months given everyone's playing catch up for various packages and what not.  Also, 20.04 is still supported until 2025, so lots of time.

**Comment by woyczek** [comment]
Ubuntu 21-10 is no more useable, and support is officially off.
We have no way but manually modifying the Vagrantfile

**Comment by bibinwilson** [comment]
Updated to 22.04
