### ISSUE TITLE
Update Ubuntu Version

### ISSUE THREAD

**Issue by akram09** [techiescamp/vagrant-kubeadm-kubernetes#18]
The current vagrant setup is based on the **21.10** ubuntu version which is now being deprecated and it does not have any support from the ubuntu team [end of life](https://lists.ubuntu.com/archives/ubuntu-announce/2022-July/000281.html). 
As a result when I tried to run the vagrant setup with `vagrant up` I got several errors from the command `apt-get update -y` saying that the links has no release files 
```E: The repository 'http://us.archive.ubuntu.com/ubuntu impish Release' no longer has a Release file.```
The best solution would be to move to **20.04** which has support until 2030.

**Comment by bibinwilson** [comment]
Issue rectified by updating the image.
