### ISSUE TITLE
[Linux][MacOS] private network (Host-Only) creational error.

### ISSUE THREAD

**Issue by Elanza-48** [techiescamp/vagrant-kubeadm-kubernetes#21]
The error exists in Linux and MacOS platforms, due to the change made in restricting the host-only network ranges on the given platforms to CIDR: 192.168.56.1/21.

The issue affects ```vagrant up``` to fail.

check the issue: [stackoverflow](https://stackoverflow.com/questions/69728426/e-accessdenied-when-creating-a-host-only-interface-on-virtualbox-via-vagrant)
solutions: [virtualbox docs](https://www.virtualbox.org/manual/ch06.html#network_hostonly)

**Comment by techiescamp** [comment]
The latest update allows you to add a range according to your preference in the settings.yaml file.
