### ISSUE TITLE
Problem with installing while vagrant up command

### ISSUE THREAD

**Issue by 3xperthulk** [techiescamp/vagrant-kubeadm-kubernetes#28]
master: Err:1 http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.25/xUbuntu_20.04  cri-o 1.25.2~0
    master:   Error reading from server. Remote end closed connection [IP: 197.155.77.1 80]
    master: Fetched 3,717 kB in 15min 35s (3,973 B/s)
    master: E: Failed to fetch http://opensuse.mirror.liquidtelecom.com//repositories/devel%3A/kubic%3A/libcontainers%3A/stable%3A/cri-o%3A/1.25/xUbuntu_20.04/amd64/cri-o_1.25.2~0_amd64.deb  Error reading from server. Remote end closed connection [IP: 197.155.77.1 80]
    master: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by 3xperthulk** [comment]
Installing on Windows 10

**Comment by eyonkerepwed** [comment]
@techiescamp ,  i had similar issues, i follow the below steps which resolved it.

Open up the command prompt of your windows as an administrator and run :
 bcdedit /set hypervisorlaunchtype off
Restart your computer.
once botted, you can destroy the previous state by running vagrant destroy.
then start the whole steps with vagrant up. that should work😀!

**Comment by techiescamp** [comment]
Fixed
