### ISSUE TITLE
GPG error while installing kubectl,kubelet,kubeadm packages

### ISSUE THREAD

**Issue by tyaprak** [techiescamp/vagrant-kubeadm-kubernetes#47]
Hi,all

I'm trying to deploy a kubernetes cluster to practice CKA exam. I followed kubernetes documentation last night and got the same error message. I assume that I did something wrong, then I tried this repo which a friend of mine suggested. After "vagrant up" command I got following error messages and the progress stopped with a non-zero exit status. 

I am thinking of two possible causes to this error:
1- The key was not properly added to the keyring since apt-key is deprecated and ubuntu is suggesting to use trusted.gpg.d
2- The key is outdated.

`master:   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05
    master: Reading package lists...
    master: W: GPG error: https://packages.cloud.google.com/apt kubernetes-xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05
    master: E: The repository 'https://apt.kubernetes.io kubernetes-xenial InRelease' is not signed.`

Has anybody faced with this problem? If so, I am open for any solution suggestions. Thanks.

**Comment by tyaprak** [comment]
I see a pull request regarding my problem, which edits common.sh deleting trusted=yes parameter. Yet, it is not solving the problem.

**Comment by ahmednreldin** [comment]
i've added this command
"sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6494C6D6997C215E" 
at the beginning of "common.sh" script and its work

**Comment by HollowMan6** [comment]
> i've added this command
> "sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6494C6D6997C215E"
> at the beginning of "common.sh" script and its work

I opened a PR for updating their address at #46 I think the key shouldn’t be hardcoded since they can depreciate that key at any time.
