### ISSUE TITLE
recommended.yaml is not valid: parse error

### ISSUE THREAD

**Issue by BasharDlale** [techiescamp/vagrant-kubeadm-kubernetes#51]
node01: error: the URL passed to filename "https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0\r/aio/deploy/recommended.yaml" is not valid: parse "https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0\r/aio/deploy/recommended.yaml": net/url: invalid control character in URL

**Comment by techiescamp** [comment]
Fixed
