### ISSUE TITLE
Proposal for VMware Desktop Integration in Vagrantfile for MacOS M2 Compatibility

### ISSUE THREAD

**Issue by w1593950** [techiescamp/vagrant-kubeadm-kubernetes#57]
I've been working with the Vagrantfile provided, and I must say, it's exceptionally well-structured and easy to follow – great job on this!

I wanted to discuss a small adjustment that could enhance our workflow, particularly for MacOS users. As you might be aware, VirtualBox currently faces some compatibility issues with MacOS, especially with the newer M2 chips. This has led to some challenges in maintaining a consistent development environment across our team.

To ensure smooth and efficient development for everyone, I was wondering if we could consider configuring our Vagrant environment to use VMware Desktop, particularly for MacOS M2 users. VMware Desktop is known for its robust support and compatibility with MacOS, and this change could significantly improve our development experience.

I understand this might require some additional adjustments to our current setup, and I'm more than willing to assist or lead the transition if needed. Your thoughts and guidance on this matter would be greatly appreciated.

Thank you for considering this request and for your continuous support in creating an effective development environment for all of us.

**Comment by kagodarog** [comment]
@w1593950, you may test this configuration that I created for m1 pro using VMware as a provider. https://github.com/kagodarog/vagrant-kubeadm-kubernetes

**Comment by techiescamp** [comment]
@w1593950 Created it in a new repo.

https://github.com/techiescamp/vagrant-kubeadm-mac-silicon
